### ISSUE TITLE
File ending case sensitive

### ISSUE THREAD

**Issue by svendhhh** [bozaro/git-lfs-migrate#43]
I've just run the migration tool on a project with, among many others, `*.dll` specified as files to migrate to LFS. This worked for the majority of files, but there was one file `somefilename.DLL` which wasn't.

There was a warning about this being tracked, but not a pointer when I cloned the project.

This suggests that `*.dll` in the `.gitattributes` is handled in a case insensitive way by `git lfs`, but that `git-lfs-migrate` is case sensitive. It should probably behave the same way as `git lfs` and include any casing of the filters.

**Comment by bozaro** [comment]
Unfortunately this `git` behavior is platform specific.
Git handle file extensions case insensitive only on case insensitive file systems (Windows). But if you try checkout converted `*.DLL` files on case sensitive file system (Linux) then you case see pointer data instead of file content.
I strongly recommend add both file mask in `.gitattributes`.
